-- VLM 识别位置 → hover → OCR tooltip → 自动生成映射表
package.path = "/usr/local/lualib/?.lua;/usr/local/lualib/?/init.lua;./lua/?.lua;./?.lua;" .. (package.path or "")
package.cpath = "/usr/local/lualib/?.so;" .. (package.cpath or "")

local ffi = require("ffi")
ffi.cdef[[void usleep(unsigned int);]]

local ocr = require("wechat_ocr")
local dir = "/opt/my-agent/wechat-ocr"
local ok, err = ocr.init(
    dir.."/models/ch_PP-OCRv4_det_infer.onnx",
    dir.."/models/ch_PP-OCRv4_rec_infer.onnx",
    dir.."/ppocr_keys_v1.txt"
)
if not ok then print("OCR init failed: "..tostring(err)); os.exit(1) end

local robot = require("wechat_robot")
robot.init()

print("--- Step 1: VLM scan ---")
local icons, err = robot.scan_icons()
if not icons then print("scan_icons failed: " .. tostring(err)); os.exit(1) end
print(string.format("VLM identified %d icons\n", #icons))

-- 点窗口左上角让微信获得内部焦点
local win = robot.get_window_rect()
if win then
    os.execute(string.format("xdotool mousemove %d %d click 1 2>/dev/null", win.x + 10, win.y + 10))
    ffi.C.usleep(1000000)
end

-- 取 baseline OCR（无 hover 时的文字）
local function ocr_boxes()
    local d, _ = ocr.capture_raw()
    if not d or not d.boxes then return {} end
    local out = {}
    for _, b in ipairs(d.boxes) do
        out[b.y .. ":" .. b.x] = b.text
    end
    return out
end
local baseline = ocr_boxes()

print("--- Step 2: Hover + OCR tooltips ---")
local results = {}
for i, icon in ipairs(icons) do
    local cleaned = "?"

    if icon.pos then
        os.execute(string.format("xdotool mousemove %d %d 2>/dev/null", icon.pos.x, icon.pos.y))
        ffi.C.usleep(600000)

        local data, _ = ocr.capture_raw()
        if data and data.boxes then
            -- 找 y 位置匹配的中文短文字，且 baseline 中没有的（即 tooltip）
            for _, b in ipairs(data.boxes) do
                local cy = b.y + b.h / 2
                local dy = cy - icon.pos.y
                local len = #(b.text or "")
                if math.abs(dy) < 40 and len >= 3 and len <= 12 and b.text:match("[\200-\237]") then
                    local key = b.y .. ":" .. b.x
                    if not baseline[key] then
                        cleaned = b.text:match("^%s*(.-)%s*$") or b.text
                        break
                    end
                end
            end
        end
    end

    print(string.format("  %d. %-12s → '%s'", i, icon.name, cleaned))
    table.insert(results, {name = icon.name, name_cn = cleaned, desc = icon.desc})
end

print("\n--- Step 3: Generated Lua mapping ---")
print("-- Auto-generated by test_gen_mapping.lua\n")
print("local M = {}\n")
print("M.defaults = {")
for i, r in ipairs(results) do
    if r.name_cn ~= "?" then
        print(string.format('    %-12s = { name_cn = "%s", name_en = "%s", desc = "%s" },',
            r.name, r.name_cn, r.name, r.desc or ""))
    end
end
print("}")
print("\nreturn M")

robot.vlm_free()
ocr.destroy()
